#!/usr/bin/env python
# flake8: noqa

import os
import readline
from pprint import pprint

from flask import *

from assignment_dashboard import *
from assignment_dashboard.database import *
from assignment_dashboard.models import *

os.environ['PYTHONINSPECT'] = 'True'
