#!/usr/bin/env python
# flake8: noqa

"""Start a REPL with convenient globals imported at top-level.

This file uses the technique from http://flask.pocoo.org/snippets/23/.
"""

import os
import readline
from pprint import pprint

from assignment_dashboard.shelltools import *

os.environ['PYTHONINSPECT'] = 'True'
